<?php

use Drupal\Core\Url;
use Drupal\user\Entity\User;
use Drupal\node\Entity\Node;
use Drupal\taxonomy\Entity\Term;
use Drupal\Core\Form\FormStateInterface;

/**
 * Impelements hook_theme().
 */
function spc_main_theme($existing, $type, $theme, $path){
  return [
    'main_banner_block' => [
      'variables' => [
        'data' => null
      ]
    ],
    'topic_banner_block' => [
      'variables' => [
        'data' => null
      ]
    ],      
    'spc_dashboard_transform_chart_block' => [
      'variables' => [
        'data' => null
      ],
    ],
    'spc_footer_partners' => [
      'variables' => [
        'partners' => null
      ]
    ],
    'spc_home_page' => [
      'variables' => [
        'data' => null
      ]
    ],      
  ];
}

/**
 * Implements hook_cron().
 */
function spc_main_cron() {
  // Getting Dataset Publications count for placing in country EEZ entity. 
  $spcPublicationImport = \Drupal::service('spc_publication_import.spcPublicationImport');
  $countries_tax =\Drupal::entityTypeManager()->getStorage('taxonomy_term')->loadTree('country');
  foreach($countries_tax as $country_term){
    $country = Term::load($country_term->tid);
    $country_code = $country->get('field_country_code')->getValue()[0]['value'];
    $datasets_count = $spcPublicationImport->get_ckan_country_datasets_count($country_code);
    $country->set('field_datasets_count', $datasets_count);
    $country->save();
  }
}
